// Generated by apps/web/scripts/generate-worker-routes.mjs — do not edit by hand.
export const spaRoutes = [
  '/',
  '/members',
  '/blog',
  '/blog/getting-started-with-the-template',
  '/blog/structured-data-without-the-headache',
] as const;
